-- =============================================================================
-- FEMALE EARNINGS INFRASTRUCTURE
--
-- Mirror image of the male coin-balance + ledger pair built in the payments
-- domain. Females earn coins when chat requests are accepted; the same
-- coins debit when payouts ship.
--
-- Conventions matching the male side:
--   * Balance column lives on the role table (`females.earnings_balance_coins`)
--     and is the source of truth for the current balance.
--   * `female_earnings` is the append-only ledger — every movement gets one
--     row with the post-mutation balance snapshot for audit.
--   * `credit_female_earnings()` is the ONLY function that may write either
--     side. SECURITY DEFINER + FOR UPDATE row lock + service_role-only.
--
-- Schema adaptation:
--   The prompt template references `females.user_id`; this codebase uses
--   `females.id` as the PK (which is itself a FK → users.id). All locks /
--   inserts use `id`, not `user_id`.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- earnings_balance_coins on females
-- ---------------------------------------------------------------------------
ALTER TABLE public.females
  ADD COLUMN IF NOT EXISTS earnings_balance_coins INTEGER NOT NULL DEFAULT 0
    CHECK (earnings_balance_coins >= 0);

COMMENT ON COLUMN public.females.earnings_balance_coins IS
  'Female''s current earnings balance in coins. Credited on accepted chat request; debited on payout. Mutated ONLY via credit_female_earnings(). Always non-negative (CHECK).';

-- Partial index — most females have zero balance most of the time; the
-- earnings dashboard only cares about non-zero rows.
CREATE INDEX IF NOT EXISTS females_earnings_balance_idx
  ON public.females (earnings_balance_coins)
  WHERE earnings_balance_coins > 0;

-- ---------------------------------------------------------------------------
-- earning_transaction_type enum
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'earning_transaction_type') THEN
    CREATE TYPE public.earning_transaction_type AS ENUM (
      'chat_earning',            -- credit from an accepted chat request
      'chat_earning_reversed',   -- credit reversed (admin / state-update failure)
      'payout',                  -- debit when a payout ships
      'payout_failed_reversal',  -- credit back when an in-flight payout fails
      'admin_adjustment'         -- catch-all manual adjustment by admin
    );
  END IF;
END$$;

COMMENT ON TYPE public.earning_transaction_type IS
  'Reason codes for entries in female_earnings. chat_earning is the only positive entry generated by the chat-request flow; reversals and admin adjustments cover the failure / dispute paths.';

-- ---------------------------------------------------------------------------
-- female_earnings ledger
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.female_earnings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  female_id UUID NOT NULL REFERENCES public.users (id) ON DELETE RESTRICT,
  type public.earning_transaction_type NOT NULL,
  -- Positive = credit, negative = debit. Zero is rejected by credit_female_earnings().
  amount_coins INTEGER NOT NULL CHECK (amount_coins <> 0),
  -- Snapshot of females.earnings_balance_coins immediately after this entry.
  balance_after_coins INTEGER NOT NULL CHECK (balance_after_coins >= 0),
  -- Soft FK — typically chat_requests.id or payouts.id depending on `type`.
  -- Not a hard FK because the referenced table varies.
  reference_id UUID,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.female_earnings IS
  'Append-only ledger of female earnings movements. Mirror of coin_transactions for males. Writes only via credit_female_earnings().';
COMMENT ON COLUMN public.female_earnings.amount_coins IS
  'Signed amount. Positive = credit (earnings, reversals back to female). Negative = debit (payout). Zero rejected.';
COMMENT ON COLUMN public.female_earnings.balance_after_coins IS
  'Snapshot of females.earnings_balance_coins right after this entry was written. Audit-friendly running total.';
COMMENT ON COLUMN public.female_earnings.reference_id IS
  'Soft FK to the source row (chat_requests.id for chat_earning, payouts.id for payout, etc.). NULL for admin adjustments.';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS female_earnings_female_id_created_at_idx
  ON public.female_earnings (female_id, created_at DESC);

CREATE INDEX IF NOT EXISTS female_earnings_reference_id_idx
  ON public.female_earnings (reference_id)
  WHERE reference_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS female_earnings_type_idx
  ON public.female_earnings (type);

-- ---------------------------------------------------------------------------
-- RLS — female sees own rows only; no write policies (service-role-only writes).
-- ---------------------------------------------------------------------------
ALTER TABLE public.female_earnings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS female_earnings_select_own ON public.female_earnings;
CREATE POLICY female_earnings_select_own
  ON public.female_earnings
  FOR SELECT
  USING (auth.uid() = female_id);

COMMENT ON POLICY female_earnings_select_own ON public.female_earnings IS
  'Female sees her own ledger entries only. No write policies exist — all writes go through credit_female_earnings() under service_role.';

-- ---------------------------------------------------------------------------
-- credit_female_earnings() — the ONE function that mutates earnings balance.
--
--   * SECURITY DEFINER bypasses RLS for the lock + write.
--   * `FOR UPDATE` row lock serialises concurrent credits/debits for the
--     same female (e.g. a chat accept racing a payout debit).
--   * Validates non-zero amount + non-negative result; raises with a
--     specific SQLSTATE so callers can branch on the failure.
--   * Returns the new id + previous/new balance for audit + UX.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.credit_female_earnings(
  p_female_id     UUID,
  p_amount        INTEGER,
  p_type          public.earning_transaction_type,
  p_reference_id  UUID DEFAULT NULL,
  p_description   TEXT DEFAULT NULL
)
RETURNS TABLE (
  earning_id              UUID,
  previous_balance_coins  INTEGER,
  new_balance_coins       INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_current_balance INTEGER;
  v_new_balance     INTEGER;
  v_earning_id      UUID;
BEGIN
  IF p_amount = 0 THEN
    RAISE EXCEPTION 'credit_female_earnings called with amount = 0'
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT earnings_balance_coins
    INTO v_current_balance
    FROM public.females
   WHERE id = p_female_id
   FOR UPDATE;

  IF v_current_balance IS NULL THEN
    RAISE EXCEPTION 'Female user not found: %', p_female_id
      USING ERRCODE = 'no_data_found';
  END IF;

  v_new_balance := v_current_balance + p_amount;

  IF v_new_balance < 0 THEN
    RAISE EXCEPTION 'Insufficient earnings balance: have=%, attempting change=%',
                    v_current_balance, p_amount
      USING ERRCODE = 'check_violation';
  END IF;

  UPDATE public.females
     SET earnings_balance_coins = v_new_balance
   WHERE id = p_female_id;

  INSERT INTO public.female_earnings
    (female_id, type, amount_coins, balance_after_coins, reference_id, description)
  VALUES
    (p_female_id, p_type, p_amount, v_new_balance, p_reference_id, p_description)
  RETURNING id INTO v_earning_id;

  RETURN QUERY SELECT v_earning_id, v_current_balance, v_new_balance;
END;
$$;

COMMENT ON FUNCTION public.credit_female_earnings(UUID, INTEGER, public.earning_transaction_type, UUID, TEXT) IS
  'The ONLY function permitted to mutate females.earnings_balance_coins. Atomic FOR UPDATE lock + balance write + ledger append. Service role only.';

REVOKE EXECUTE ON FUNCTION public.credit_female_earnings(UUID, INTEGER, public.earning_transaction_type, UUID, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.credit_female_earnings(UUID, INTEGER, public.earning_transaction_type, UUID, TEXT) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.credit_female_earnings(UUID, INTEGER, public.earning_transaction_type, UUID, TEXT) FROM anon;
GRANT  EXECUTE ON FUNCTION public.credit_female_earnings(UUID, INTEGER, public.earning_transaction_type, UUID, TEXT) TO service_role;
